### ISSUE TITLE
ExtractedResources - Error 401 (permissions).

### ISSUE THREAD

**Issue by Koubek** [NAVDOCKER/GENERIC#5]
When accessing via Web Client I have problems with the icons. The icons are presented via links leading into `C:\ProgramData\Microsoft\Microsoft Dynamics NAV\100\Web Client\NAV\WebClient\Resources\ExtractedResources` folder. The folder exists and the resources as well.

It looks like in the case of non-Windows authentication the user does not have permissions...
![image](https://user-images.githubusercontent.com/24265973/27703298-2d62d124-5d07-11e7-81d3-9a2959f4ef83.png)

The error:
![image](https://user-images.githubusercontent.com/24265973/27703335-4cd83878-5d07-11e7-8f38-1510e3c6ab45.png)

**Comment by tfenster** [comment]
I had the same issue with Windows Auth, could solve it by making the fake user inside the Container member of the admin group

**Comment by Koubek** [comment]
Yes, I could solve the problem as well adding thick hack but... Maybe for containers, it should be OK (in other cases I would consider it as a security concern :) ).

**Comment by freddydk** [comment]
This is fixed by giving everyone ReadAndExecute rights to the ExtractedResources folder. I have fixed this and checked in - I have also created a new generic on navdocker.azurecr.io/dynamics-nav-generic and I have created a W1 of 2017 CU8 here navdocker.azurecr.io/dynamics-nav:2017.
I will kickoff all local builds of CU8 now - they will be on navdocker.azurecr.io later today with this fix.

**Comment by Koubek** [comment]
I`ll try them. Thanks.
